const bazaar_items = [
						'Hardstone',
            'Cobblestone',
						'Coal',
						'Iron Ingot',
						'Gold Ingot',
						'Lapis Lazuli',
						'Redstone',
						'Emerald',
						'Diamond',
						'Mithril',
						'Titanium',
						'Gemstone',
						'Lilypad',
						'Gold Nugget',
						'Blaze Rod',
						'Enchanted Gold Ingot',
						'Enchanted Blaze Rod',
						'Magma Cream',
						'Bone',
						'Enchanted Magma Cream',
						'Enchanted Bone',
						'Enchanted Coal',
						'Ghast Tear',
						'Enchanted Ghast Tear',
						'Ender Pearl',
						'Enchanted Ender Pearl',
						'Eye of Ender',
						'Enchanted Eye of Ender',
						'Obsidian',
						'Enchanted Obsidian',
						'Summoning Eye',
						'Arrow',
						'Slimeball',
						'String',
						'Spider Eye',
						'Enchanted Slimeball',
						'Enchanted String',
						'Enchanted Spider Eye',
						'Rotten Flesh',
						'Carrot',
						'Potato',
						'Shark Fin',
					];

const ah_items = [
  "Recombobulator 3000",
  "Dragon Claw",
  "Wither Blood",
  "Warped Stone",
  "Deep Sea Orb",
  "Dragon Horn",
  "Precursor Gear",
  "Sadan's Brooch",
  "Hardened Wood",
  "Lucky Dice",
  "Onyx",
  "Diamonite",
  "Rock Gemstone",
];

module.exports = { bazaar_items, ah_items }